package org.example.project.core.enums

enum class AlertType() {
    Default(),
    Duplication(),
    Null(),
    SendEmailSuccess(),
    Success(),
    EmailOrPasswordNull(),
    TokenExpired(),
    EmailNotValid(),
    PasswordNotValid(),
    AccountInactive(),
    ProductNotFound(),
    UpdateOrderSuccess(),
    ProductNameNull(),
    ProductStockNull(),
    ProductPriceNull(),
    ProductAvailableNull(),
    CartSelectedNull(),
    MissingPersonalInfo(),
    PlaceOrderSuccessful(),
    AddressNull(),
    PaymentNull(),
    VoucherCodeNull(),
    VoucherDiscountNull(),
    VoucherMaxUseNull(),
    VoucherActiveNull(),
}